exports.findPlan = (plan_id) => {
  const plans = ["Basic", "Business", "Starter", "Pro"];
//   const plans = ["Basic", "Business", "Unlimited", "Starter", "Essential", "Advanced", "Leader"];
  return plans.find((plan) => plan_id.toLowerCase().includes(plan.toLowerCase())) || null;
};

exports.findPlanPeriod = (plan_id) => {
  if (plan_id.includes("Monthly")) {
    return "month";
  } else if (plan_id.includes("Yearly")) {
    return "year";
  } else {
    return "quater";
  }
};

exports.findPlanCurr = (plan_id) => {
  if (plan_id.includes("USD")) {
    return "$";
  } else {
    return "€";
  }
};

exports.findPlanCurrName = (plan_id) => {
  if (plan_id.includes("USD")) {
    return "USD";
  } else {
    return "EUR";
  }
};

// New Plans from Chargebee or Terms
exports.Terms = [
   {
    id: 121,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-USD-Monthly",
    currency_code: "USD",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "49",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 127,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-USD-Every-3-months",
    currency_code: "USD",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "132",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 133,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-USD-Yearly",
    currency_code: "USD",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "441",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 122,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-EUR-Monthly",
    currency_code: "EUR",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "49",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 128,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-EUR-Every-3-months",
    currency_code: "EUR",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "132",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 134,
    subdomain: "app",
    plan_name: null,
    plan_id: "Starter-Novalya-EUR-Yearly",
    currency_code: "EUR",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "441",
    amount_2: "97",
    plan_type: "Novalya-all",
    connections: 1,
    limits: "Starter",
    old_plan: ["Starter"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 123,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-USD-Monthly",
    currency_code: "USD",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "89",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 129,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-USD-Every-3-months",
    currency_code: "USD",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "240",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 135,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-USD-Yearly",
    currency_code: "USD",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "801",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 124,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-EUR-Monthly",
    currency_code: "EUR",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "89",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 130,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-EUR-Every-3-months",
    currency_code: "EUR",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "240",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 136,
    subdomain: "app",
    plan_name: null,
    plan_id: "Essential-Novalya-EUR-Yearly",
    currency_code: "EUR",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "801",
    amount_2: "197",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Essential",
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 125,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-USD-Monthly",
    currency_code: "USD",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "149",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 131,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-USD-Every-3-months",
    currency_code: "USD",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "402",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 137,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-USD-Yearly",
    currency_code: "USD",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "1341",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 126,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-EUR-Monthly",
    currency_code: "EUR",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "149",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 132,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-EUR-Every-3-months",
    currency_code: "EUR",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "402",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 138,
    subdomain: "app",
    plan_name: null,
    plan_id: "Advanced-Novalya-EUR-Yearly",
    currency_code: "EUR",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "1341",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Advanced",
    old_plan: ["Basic", "Pro"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 125,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-USD-Monthly",
    currency_code: "USD",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "297",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 131,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-USD-Every-3-months",
    currency_code: "USD",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "711",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 137,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-USD-Yearly",
    currency_code: "USD",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "2316",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 126,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-EUR-Monthly",
    currency_code: "EUR",
    period_unit: "month",
    family_id: "Novalya",
    amount_1: "297",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 132,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-EUR-Every-3-months",
    currency_code: "EUR",
    period_unit: "quater",
    family_id: "Novalya",
    amount_1: "711",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
  {
    id: 138,
    subdomain: "app",
    plan_name: null,
    plan_id: "Unlimited-Novalya-EUR-Yearly",
    currency_code: "EUR",
    period_unit: "year",
    family_id: "Novalya",
    amount_1: "2316",
    amount_2: "297",
    plan_type: "Novalya-all",
    connections: 2,
    limits: "Unlimited_new",
    old_plan: ["Business"],
    trial: "Yes",
    status: 1,
    type:"revamp"
  },
];